### ISSUE TITLE
Make list conform to awesome-list

### ISSUE THREAD

**Issue by fkromer** [brunopulis/awesome-cypress#3]
**Is your feature request related to a problem? Please describe.**

One does not have all resources on a single page. This makes browsing the page no fun.

**Describe the solution you'd like**

I'd suggest to make the list conform to [sindresorhus/awesome](https://github.com/sindresorhus/awesome).

**Comment by brunopulis** [comment]
Hi @fkromer, I'm sorry for the delay, I even thought of putting it in the awesome-list format, however, I realize that Cypress has many features and being only in the README could be very confusing.

**Comment by fkromer** [comment]
@brunopulis It's your repo. It's your choice.
